# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class NewGUI(QtWidgets.QMainWindow):
    EXIT_CODE_REBOOT = -123
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        self.logging_movie = QtGui.QMovie("images\\sea.gif")
        self.video_label.setMovie(self.logging_movie)
        self.video_label.raise_()
        self.opacity_effect = QtWidgets.QGraphicsOpacityEffect()
        self.opacity_effect.setOpacity(0.35)
        self.video_label.setGraphicsEffect(self.opacity_effect)
        self.logging_movie.start()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(440, 450)
        MainWindow.setMinimumSize(QtCore.QSize(440, 450))
        MainWindow.setMaximumSize(QtCore.QSize(440, 450))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle("Q-Soft: Code submit and checkout assistant")
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setToolTip("")
        MainWindow.setToolTipDuration(-1)
        MainWindow.setStatusTip("")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(440, 450))
        self.centralwidget.setMaximumSize(QtCore.QSize(440, 450))
        self.centralwidget.setStyleSheet("QFrame#frame_4{\n"
"background-color: rgb(0, 170, 255, .5);\n"
"border: 1px solid black;\n"
"}\n"
".QFrame{\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton{\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(0, 240, 240);\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"}\n"
"QLineEdit{\n"
"border-radius: 5px;\n"
"border: 1px solid black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 440, 450))
        self.frame_4.setMinimumSize(QtCore.QSize(440, 450))
        self.frame_4.setMaximumSize(QtCore.QSize(440, 450))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(20, 0, 20, 20)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_5.setFont(font)
        self.frame_5.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"background-color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(0, 240, 240);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 0, 0);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Backup = QtWidgets.QPushButton(self.frame_5)
        self.Backup.setMinimumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Backup.setFont(font)
        self.Backup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Backup.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Backup.setToolTip("Click to create a backup\n"
" for current local folder.")
        self.Backup.setAutoDefault(False)
        self.Backup.setDefault(True)
        self.Backup.setFlat(False)
        self.Backup.setObjectName("Backup")
        self.horizontalLayout.addWidget(self.Backup)
        self.Checkout = QtWidgets.QPushButton(self.frame_5)
        self.Checkout.setMinimumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Checkout.setFont(font)
        self.Checkout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Checkout.setToolTip("Click to checkout.")
        self.Checkout.setObjectName("Checkout")
        self.horizontalLayout.addWidget(self.Checkout)
        self.Checkin = QtWidgets.QPushButton(self.frame_5)
        self.Checkin.setMinimumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Checkin.setFont(font)
        self.Checkin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Checkin.setToolTip("Click to commit")
        self.Checkin.setObjectName("Checkin")
        self.horizontalLayout.addWidget(self.Checkin)
        self.gridLayout.addWidget(self.frame_5, 2, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 145))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 145))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_7.setStyleSheet("QPushButton{\n"
"border: 0px;\n"
"border-radius: 5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Minimize = QtWidgets.QPushButton(self.frame_7)
        self.Minimize.setMinimumSize(QtCore.QSize(30, 25))
        self.Minimize.setMaximumSize(QtCore.QSize(35, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Minimize.setFont(font)
        self.Minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Minimize.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Minimize.setToolTip("Minimize")
        self.Minimize.setToolTipDuration(-1)
        self.Minimize.setIconSize(QtCore.QSize(0, 0))
        self.Minimize.setAutoDefault(False)
        self.Minimize.setDefault(True)
        self.Minimize.setFlat(False)
        self.Minimize.setObjectName("Minimize")
        self.horizontalLayout_4.addWidget(self.Minimize)
        self.Close = QtWidgets.QPushButton(self.frame_7)
        self.Close.setMinimumSize(QtCore.QSize(30, 25))
        self.Close.setMaximumSize(QtCore.QSize(35, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Close.setFont(font)
        self.Close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Close.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Close.setToolTip("Close")
        self.Close.setToolTipDuration(-1)
        self.Close.setIconSize(QtCore.QSize(0, 0))
        self.Close.setAutoDefault(False)
        self.Close.setDefault(True)
        self.Close.setFlat(False)
        self.Close.setObjectName("Close")
        self.horizontalLayout_4.addWidget(self.Close)
        self.verticalLayout_4.addWidget(self.frame_7, 0, QtCore.Qt.AlignRight)
        self.frame_3 = QtWidgets.QFrame(self.frame_8)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QPushButton{\n"
"border-radius: 10px;\n"
"border: 1px solid black;\n"
"background-color: white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(0, 240, 240);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 0, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GitBrowser = QtWidgets.QPushButton(self.frame)
        self.GitBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GitBrowser.sizePolicy().hasHeightForWidth())
        self.GitBrowser.setSizePolicy(sizePolicy)
        self.GitBrowser.setMinimumSize(QtCore.QSize(90, 25))
        self.GitBrowser.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.GitBrowser.setFont(font)
        self.GitBrowser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GitBrowser.setMouseTracking(False)
        self.GitBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.GitBrowser.setToolTip("Click to choose git\'s folder.")
        self.GitBrowser.setToolTipDuration(-1)
        self.GitBrowser.setAutoFillBackground(False)
        self.GitBrowser.setStyleSheet("")
        self.GitBrowser.setDefault(True)
        self.GitBrowser.setFlat(False)
        self.GitBrowser.setObjectName("GitBrowser")
        self.verticalLayout.addWidget(self.GitBrowser)
        self.LocalBrowser = QtWidgets.QPushButton(self.frame)
        self.LocalBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LocalBrowser.sizePolicy().hasHeightForWidth())
        self.LocalBrowser.setSizePolicy(sizePolicy)
        self.LocalBrowser.setMinimumSize(QtCore.QSize(90, 25))
        self.LocalBrowser.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.LocalBrowser.setFont(font)
        self.LocalBrowser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LocalBrowser.setMouseTracking(False)
        self.LocalBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.LocalBrowser.setToolTip("Click to choose local folder.")
        self.LocalBrowser.setToolTipDuration(-1)
        self.LocalBrowser.setAutoFillBackground(False)
        self.LocalBrowser.setStyleSheet("")
        self.LocalBrowser.setDefault(True)
        self.LocalBrowser.setFlat(False)
        self.LocalBrowser.setObjectName("LocalBrowser")
        self.verticalLayout.addWidget(self.LocalBrowser)
        self.BackupBrowser = QtWidgets.QPushButton(self.frame)
        self.BackupBrowser.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackupBrowser.sizePolicy().hasHeightForWidth())
        self.BackupBrowser.setSizePolicy(sizePolicy)
        self.BackupBrowser.setMinimumSize(QtCore.QSize(90, 25))
        self.BackupBrowser.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.BackupBrowser.setFont(font)
        self.BackupBrowser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BackupBrowser.setMouseTracking(False)
        self.BackupBrowser.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.BackupBrowser.setToolTip("Click to create a backup\n"
" for current local folder.")
        self.BackupBrowser.setToolTipDuration(-1)
        self.BackupBrowser.setAutoFillBackground(False)
        self.BackupBrowser.setStyleSheet("")
        self.BackupBrowser.setDefault(True)
        self.BackupBrowser.setFlat(False)
        self.BackupBrowser.setObjectName("BackupBrowser")
        self.verticalLayout.addWidget(self.BackupBrowser)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.GitLink = QtWidgets.QLineEdit(self.frame_2)
        self.GitLink.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.GitLink.setFont(font)
        self.GitLink.setToolTip("")
        self.GitLink.setObjectName("GitLink")
        self.verticalLayout_2.addWidget(self.GitLink)
        self.LocalLink = QtWidgets.QLineEdit(self.frame_2)
        self.LocalLink.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.LocalLink.setFont(font)
        self.LocalLink.setToolTip("")
        self.LocalLink.setObjectName("LocalLink")
        self.verticalLayout_2.addWidget(self.LocalLink)
        self.BackupLink = QtWidgets.QLineEdit(self.frame_2)
        self.BackupLink.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.BackupLink.setFont(font)
        self.BackupLink.setToolTip("")
        self.BackupLink.setText("")
        self.BackupLink.setReadOnly(True)
        self.BackupLink.setClearButtonEnabled(False)
        self.BackupLink.setObjectName("BackupLink")
        self.verticalLayout_2.addWidget(self.BackupLink)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame_8, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.frame_6.setFont(font)
        self.frame_6.setStyleSheet("QPushButton{\n"
"border: 0px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(0, 240, 240);\n"
"border-radius: 2px;\n"
"border: 0px solid black;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 0, 0);\n"
"border-radius: 2px;\n"
"border: 0px solid black;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.project_list = QtWidgets.QComboBox(self.frame_6)
        self.project_list.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.project_list.setFont(font)
        self.project_list.setToolTipDuration(-1)
        self.project_list.setAutoFillBackground(False)
        self.project_list.setStyleSheet("")
        self.project_list.setObjectName("project_list")
        self.horizontalLayout_2.addWidget(self.project_list)
        self.Restore_button = QtWidgets.QPushButton(self.frame_6)
        self.Restore_button.setMinimumSize(QtCore.QSize(30, 25))
        self.Restore_button.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Restore_button.setFont(font)
        self.Restore_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Restore_button.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Restore_button.setToolTip("Restore from backup.")
        self.Restore_button.setToolTipDuration(-1)
        self.Restore_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Restore_button.setIcon(icon)
        self.Restore_button.setIconSize(QtCore.QSize(30, 30))
        self.Restore_button.setAutoDefault(False)
        self.Restore_button.setDefault(True)
        self.Restore_button.setFlat(False)
        self.Restore_button.setObjectName("Restore_button")
        self.horizontalLayout_2.addWidget(self.Restore_button)
        self.WorkSpace = QtWidgets.QPushButton(self.frame_6)
        self.WorkSpace.setMinimumSize(QtCore.QSize(30, 25))
        self.WorkSpace.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.WorkSpace.setFont(font)
        self.WorkSpace.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.WorkSpace.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.WorkSpace.setToolTip("Click to open workspace.")
        self.WorkSpace.setToolTipDuration(-1)
        self.WorkSpace.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/off_workspace.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WorkSpace.setIcon(icon1)
        self.WorkSpace.setIconSize(QtCore.QSize(30, 30))
        self.WorkSpace.setAutoDefault(False)
        self.WorkSpace.setDefault(True)
        self.WorkSpace.setFlat(False)
        self.WorkSpace.setObjectName("WorkSpace")
        self.horizontalLayout_2.addWidget(self.WorkSpace)
        self.AddProject = QtWidgets.QPushButton(self.frame_6)
        self.AddProject.setMinimumSize(QtCore.QSize(30, 25))
        self.AddProject.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.AddProject.setFont(font)
        self.AddProject.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddProject.setToolTip("Click to add project.")
        self.AddProject.setToolTipDuration(-1)
        self.AddProject.setStyleSheet("border-radius: 2px;")
        self.AddProject.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddProject.setIcon(icon2)
        self.AddProject.setIconSize(QtCore.QSize(30, 30))
        self.AddProject.setObjectName("AddProject")
        self.horizontalLayout_2.addWidget(self.AddProject)
        self.AddTask = QtWidgets.QPushButton(self.frame_6)
        self.AddTask.setMinimumSize(QtCore.QSize(30, 25))
        self.AddTask.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AddTask.setFont(font)
        self.AddTask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddTask.setToolTip("Click to add task")
        self.AddTask.setToolTipDuration(-1)
        self.AddTask.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddTask.setStyleSheet("border-radius: 5px;")
        self.AddTask.setIconSize(QtCore.QSize(0, 0))
        self.AddTask.setObjectName("AddTask")
        self.horizontalLayout_2.addWidget(self.AddTask)
        self.gridLayout.addWidget(self.frame_6, 3, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setMinimumSize(QtCore.QSize(400, 200))
        self.frame_9.setMaximumSize(QtCore.QSize(400, 200))
        self.frame_9.setStyleSheet("border: 0px;\n"
"background: None;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.video_label = QtWidgets.QLabel(self.frame_9)
        self.video_label.setEnabled(False)
        self.video_label.setGeometry(QtCore.QRect(0, 0, 400, 200))
        self.video_label.setMinimumSize(QtCore.QSize(400, 200))
        self.video_label.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.video_label.setFont(font)
        self.video_label.setAutoFillBackground(False)
        self.video_label.setStyleSheet("border: 0px;\n"
"background: None;")
        self.video_label.setText("")
        self.video_label.setObjectName("video_label")
        self.logging_window = QtWidgets.QPlainTextEdit(self.frame_9)
        self.logging_window.setGeometry(QtCore.QRect(0, 0, 400, 200))
        self.logging_window.setMinimumSize(QtCore.QSize(400, 200))
        self.logging_window.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.logging_window.setFont(font)
        self.logging_window.setAutoFillBackground(True)
        self.logging_window.setStyleSheet("")
        self.logging_window.setObjectName("logging_window")
        self.gridLayout.addWidget(self.frame_9, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.Backup.setText(_translate("MainWindow", "Backup"))
        self.Checkout.setText(_translate("MainWindow", "Check out"))
        self.Checkin.setText(_translate("MainWindow", "Check in"))
        self.Minimize.setText(_translate("MainWindow", "–"))
        self.Close.setText(_translate("MainWindow", "X"))
        self.GitBrowser.setText(_translate("MainWindow", "Git folder"))
        self.LocalBrowser.setText(_translate("MainWindow", "Local folder"))
        self.BackupBrowser.setText(_translate("MainWindow", "Backup folder"))
        self.project_list.setToolTip(_translate("MainWindow", "Select project"))
        self.AddTask.setText(_translate("MainWindow", "⁂"))
